### ISSUE TITLE
并发1000线测试出现 sql: database is closed

### ISSUE THREAD

**Issue by onlysad** [xormplus/xorm#35]
```go
package common

import (
	"fmt"
	"github.com/xormplus/xorm"
	"sync"
	"time"
)

type DBEngine struct {
	xorm.Engine
}

var engine *DBEngine

var once sync.Once
func GetDBEngine() *DBEngine{

	once.Do(func() {
		var tmp, err = xorm.NewEngine("mysql", "root:xxxxxx@tcp(localhost:3306)/gotest?charset=utf8&parseTime=True")

		if err != nil{
			panic(err)
		}
		engine = &DBEngine{
			Engine: *tmp,
		}

		engine.DatabaseTZ = time.Local
		engine.TZLocation = time.Local
		//engine.ShowSQL(true)
		//engine.ShowExecTime(true)
		engine.SetMaxOpenConns(1000)
		engine.SetMaxOpenConns(1000)
		fmt.Println("******************************************************")
	})
	return engine
}
```
```go
package model

import (
	"time"
)

type SysUser struct {
	Id         int          `xorm:"not null pk autoincr INT(11)"`
	Name       string       `xorm:"not null VARCHAR(50)"`
	Sex        int          `xorm:"not null INT(1)"`
	CreateDate time.Time    `xorm:"not null default 'CURRENT_TIMESTAMP' TIMESTAMP <-"`
	UpdateTime time.Time    `xorm:"null default null TIMESTAMP <-"`
	Role       SysRole 		`xorm:"-"`
}

```

```go
package xorm

import (
	"encoding/json"
	"fmt"
	"testing"
	"time"
	"xorm/common"
	"xorm/model"
)

func testFn(){
	engine := common.GetDBEngine()

	session := engine.NewSession()
	defer session.Close()

	tx, e := session.BeginTrans()
	if e != nil {
		panic(e)
	}

	user := model.SysUser{}
	txsession := tx.Session()
	bool, err := txsession.ID(1).Get(&user)
	if !bool {
		panic(err)
	}
	fmt.Println(user)
	j, err := json.Marshal(user)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(j))

	res2, err := txsession.Update(&model.SysUser{
		Name:		"hhh",
	}, &model.SysUser{
		Sex:		2,
	})
	if err != nil {
		panic(err)
		txsession.Rollback()
	}
	fmt.Println(res2)
}

func Test_main(t *testing.T) {
	time.Sleep(time.Second * 5)

	for i := 0; i < 1000; i++ {
		go testFn()
	}

	time.Sleep(time.Second * 30)

	//err = role.New()
	//
	//if err != nil {
	//	panic(err)
	//}
}
```

```
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/victor/work/golang/study:/Users/victor/www/Go #gosetup
/usr/local/go/bin/go test -c -o /private/var/folders/q5/67dd_6914yq0_t43dmgx084m0000gn/T/___Test_main_in_xorm xorm #gosetup
/usr/local/go/bin/go tool test2json -t /private/var/folders/q5/67dd_6914yq0_t43dmgx084m0000gn/T/___Test_main_in_xorm -test.v -test.run ^Test_main$ #gosetup
=== RUN   Test_main
******************************************************
panic: sql: database is closed

goroutine 603 [running]:
xorm.testFn()
	/Users/victor/work/golang/study/src/xorm/xorm_test.go:20 +0x50a
created by xorm.Test_main
	/Users/victor/work/golang/study/src/xorm/xorm_test.go:52 +0x51
panic: sql: database is closed

goroutine 606 [running]:
xorm.testFn()
	/Users/victor/work/golang/study/src/xorm/xorm_test.go:20 +0x50a
created by xorm.Test_main
	/Users/victor/work/golang/study/src/xorm/xorm_test.go:52 +0x51

Process finished with exit code 1
```

数据库为Mysql，最大连接数设置为2048. 感觉像是有线程安全问题？

请帮忙解答，万分感谢。

**Comment by xormplus** [comment]
请贴全代码。看错误日志，是xorm.testUser2()和xorm.TestRole中有问题，但是没有看到相关代码。还有数据库驱动也没看到。用的什么数据库驱动？请贴全所有代码

**Comment by onlysad** [comment]
> 请贴全代码。看错误日志，是xorm.testUser2()和xorm.TestRole中有问题，但是没有看到相关代码。还有数据库驱动也没看到。用的什么数据库驱动？请贴全所有代码

不好意思，搞了一个通宵，复制代码的时候搞错了，代码已重贴。

**Comment by onlysad** [comment]
> > 请贴全代码。看错误日志，是xorm.testUser2()和xorm.TestRole中有问题，但是没有看到相关代码。还有数据库驱动也没看到。用的什么数据库驱动？请贴全所有代码
> 
> 不好意思，搞了一个通宵，复制代码的时候搞错了，代码已重贴。

但是问题此问题可能不是线程安全问题，仔细读了源码觉得不可能有问题。
然后运行监控系统线程，发现每次test启动，系统线程就会突然减少几十，
然后test这边报错，感觉就像是跟数据库之前的连接被系统给杀掉了，准备
把数据库换到另外一台Win的主机上试试。

**Comment by xormplus** [comment]
还有你现在的代码中也没看到事务commit。另外代码中有两个engine.SetMaxOpenConns(1000)，建议设置SetMaxIdleConns。同时建议你将SetMaxOpenConns设置为2000

**Comment by onlysad** [comment]
> 还有你现在的代码中也没看到事务commit。另外代码中有两个engine.SetMaxOpenConns(1000)，建议设置SetMaxIdleConns。同时建议你将SetMaxOpenConns设置为2000

打扰了，可以关闭了，确认应该是MacOS有线程限制的问题，数据库局网连接Win上的Mysql，1000并发正常无误。
